### ISSUE TITLE
Maybe Add a GitHub Changelog?

### ISSUE THREAD

**Issue by Gandalf1209** [Computerology/SheepFarmSimulator#1]
When the game updates itself, it tells me the changelog, but that's the only time I see it. Could you possibly add a changelog file to the GitHub repo?

Thanks

**Comment by Computerology** [comment]
The changelog can be found on the game's website: http://computerology.github.io/home/sheepgame

**Comment by Gandalf1209** [comment]
Ah yes, my bad -_-
